### ISSUE TITLE
Prettier getting an error on typescript file with optional chaining

### ISSUE THREAD

**Issue by rannie-peralta** [rannie-peralta/ui-guide#9]
**Expected behavior:**

Prettier should format the `.ts` file successfully.

**Comment by miluoshi** [comment]
This needs to be merged first: https://github.com/prettier/prettier/pull/6680

**Comment by rannie-peralta** [comment]
Alright, subscribing to that PR now. Thanks

**Comment by rannie-peralta** [comment]
Closed via [c51bed0](https://github.com/rannie-peralta/ui-guide/commit/c51bed043c96f9b5bc0c1b2613e8b49eaaaa6fe4)
